services:
  LCV\DoctrineODMPaginatorBundle\Pagination\Paginator:
    arguments: ["@doctrine_mongodb", "@request_stack", "",
                "", "", ""]

  LCV\DoctrineODMPaginatorBundle\Pagination\AggregationPaginator:
    arguments: ["@doctrine_mongodb", "@request_stack", "",
                "", "", ""]
